### PR TITLE
update docker file to correct port (5076)

### PR DESCRIPTION
**Pull request by dmce**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

### CODE REVIEW

**Comment by dmce** [comment]
sorry about the messy commits. only the last is a change

**Comment by calvinbui** [comment]
This needs to be merged in for some reverse proxies to work
@sparklyballs

**Comment by tobbenb** [comment]
@calvinbui Why is this needed for reverse proxy to work?
As long as you use the correct port in the docker create command, the exposed port doesn't matter.

**Comment by calvinbui** [comment]
I am using Traefik (https://traefik.io/) which listens directly on the Docker socket. It doesn't require the port to be published as it can connect directly to it through being on the same Docker network. However if the port that is being exposed by the container is incorrect, you can expect it to run into a server/gateway error.

**Comment by tobbenb** [comment]
The EXPOSE instruction doesn't publish the port at run time. It's more of a documentation for which port the container listens on. It's the -p flag that exposes the port at run time.
So the wrong port in the Dockerfile is just cosmetics. We will change it in house, as the PR got a little messy.

**Comment by sparklyballs** [comment]
already done inhouse

**Pull request closed without merging**
